language: java

jdk:
  - oraclejdk8
  
sudo: false

before_install:
  - export MAVEN_OPTS=-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn clean test jacoco:report -B

after_success:
  - mvn coveralls:report -B

before_deploy:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

deploy:
  provider: script
  script: mvn deploy -DskipTests -P release
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_success: never
    on_failure: change
    
branches:
  only:
    - master
    - dev
    - /^release.*$/
    - /^hotfix.*$/
