language: java

jdk:
  - oraclejdk8
  
sudo: false

script: mvn clean verify

after_success:
  - mvn clean -DskipTests jacoco:report coveralls:report

before_deploy:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

deploy:
  provider: script
  script: mvn deploy -DskipTests -P release
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    on_success: never
    on_failure: change
    
branches:
  only:
    - master
    - dev
    - /^release.*$/
    - /^hotfix.*$/
